
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.05 at 05:44:58 PM IST 
//


package com.dataSwitch.xml.Talend;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dataSwitch.xml.TalendFile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dataSwitch.xml.TalendFile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TalendfileProcessType }
     * 
     */
    public TalendfileProcessType createTalendfileProcessType() {
        return new TalendfileProcessType();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Node }
     * 
     */
    public TalendfileProcessType.Node createTalendfileProcessTypeNode() {
        return new TalendfileProcessType.Node();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Node.Metadata }
     * 
     */
    public TalendfileProcessType.Node.Metadata createTalendfileProcessTypeNodeMetadata() {
        return new TalendfileProcessType.Node.Metadata();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Parameters }
     * 
     */
    public TalendfileProcessType.Parameters createTalendfileProcessTypeParameters() {
        return new TalendfileProcessType.Parameters();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Context }
     * 
     */
    public TalendfileProcessType.Context createTalendfileProcessTypeContext() {
        return new TalendfileProcessType.Context();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Node.ElementParameter }
     * 
     */
    public TalendfileProcessType.Node.ElementParameter createTalendfileProcessTypeNodeElementParameter() {
        return new TalendfileProcessType.Node.ElementParameter();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Node.Metadata.Column }
     * 
     */
    public TalendfileProcessType.Node.Metadata.Column createTalendfileProcessTypeNodeMetadataColumn() {
        return new TalendfileProcessType.Node.Metadata.Column();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Parameters.ElementParameter }
     * 
     */
    public TalendfileProcessType.Parameters.ElementParameter createTalendfileProcessTypeParametersElementParameter() {
        return new TalendfileProcessType.Parameters.ElementParameter();
    }

    /**
     * Create an instance of {@link TalendfileProcessType.Parameters.RoutinesParameter }
     * 
     */
    public TalendfileProcessType.Parameters.RoutinesParameter createTalendfileProcessTypeParametersRoutinesParameter() {
        return new TalendfileProcessType.Parameters.RoutinesParameter();
    }

}