SELECT SalesOrderID,
       OrderDate,
       TotalDue,
       (SELECT COUNT(SalesOrderDetailID)
          FROM Sales.SalesOrderDetail
WHERE SalesOrderID = SO.SalesOrderID) as LineCount
FROM  Sales.SalesOrderHeader SO

(SELECT 1 AS sqlorder, CAST idw__QueryNode_2 AS sqltxt FROM dbc.dbcinfo GROUP BY 1 UNION SELECT 2 AS sqlorder, TRIM idw__QueryNode_7 || ',' || COALESCE idw__QueryNode_14 || ',' || COALESCE idw__QueryNode_18 || ',' || COALESCE idw__QueryNode_22 || ',' || COALESCE idw__QueryNode_26 || ',' || COALESCE idw__QueryNode_31 || ',' || COALESCE idw__QueryNode_37 || ',' || COALESCE idw__QueryNode_41 || ',' || COALESCE idw__QueryNode_45 || ',' || COALESCE idw__QueryNode_49 || ',' || COALESCE idw__QueryNode_55 || ',' || COALESCE idw__QueryNode_59 || ',' || COALESCE idw__QueryNode_63 || ',' || COALESCE idw__QueryNode_67 || ',' || COALESCE idw__QueryNode_71 || ',' || COALESCE idw__QueryNode_75 || ',' || COALESCE idw__QueryNode_79 || ',' || COALESCE idw__QueryNode_83 || ',' || COALESCE idw__QueryNode_87 || ',' || COALESCE idw__QueryNode_91 || ',' || COALESCE idw__QueryNode_95 || ',' || COALESCE idw__QueryNode_99 || ',' || COALESCE idw__QueryNode_103 || ',' || COALESCE idw__QueryNode_107 || ',' || COALESCE idw__QueryNode_111 || ',' || COALESCE idw__QueryNode_116 || ',' || COALESCE idw__QueryNode_120 || ',' || COALESCE idw__QueryNode_124 FROM ${EDW_OS_VEDWDB}.prop_desc_multi AS T13, ${EDW_OS_VEDWDB}.pdb_trip_hdr AS T6, ${EDW_OS_WORKDB}.inside_sales_dmid as ISList, ${EDW_OS_VEDWDB}.guest AS T1 LEFT OUTER JOIN ${EDW_OS_VEDWDB}.gst_tier AS T7 ON T1.i_dmid= T7.i_dmid LEFT OUTER JOIN ${EDW_OS_VEDWDB}.guest_ethnicity AS T15 ON T1.i_dmid= T15.i_dmid LEFT OUTER JOIN ${EDW_OS_VEDWDB}.guest_game5_dedup AS T8 ON T8.i_dmid= T1.i_dmid LEFT JOIN ${EDW_OS_VEDWDB}.gst_personal T9 ON T1.i_dmid= T9.i_dmid LEFT OUTER JOIN ${EDW_OS_VEDWDB}.guest_ethnicity_append_dedup AS T10 ON T10.i_dmid= T1.i_dmid LEFT JOIN ${EDW_OS_VEDWDB}.gst_prop_mail_code T11 ON T1.i_dmid= T11.i_dmid LEFT JOIN ${EDW_OS_VEDWDB}.gst_email T14 ON T1.i_dmid= T14.i_dmid LEFT OUTER JOIN ${EDW_OS_VEDWDB}.gst_addr_hdr T12 ON T1.i_dmid= T12.i_dmid AND T12.c_addr_type= T1.c_addr_pref LEFT JOIN ${EDW_OS_VEDWDB}.zip_desc T100 ON T12.c_zip_7= T100.c_zip_cd WHERE T13.c_prop_cd= T1.c_dom_cd AND T13.i_prop_market_type_id= 1 AND T1.i_dmid= T6.i_dmid AND T6.d_end_dt > idw__QueryNode_126 - INTERVAL '3' YEAR and T1.i_dmid= ISLIST.i_dmid), idw__QueryNode_128=(SELECT sqltxt idw__QueryNode_0 FROM idw__QueryNode_127 AS exporttxt ORDER BY sqlorder;)


idw__QueryNode_128=(SELECT sqltxt idw__QueryNode_0 FROM idw__QueryNode_127 AS exporttxt ORDER BY sqlorder;)