
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceDataElementRef" type="{}sourceDataElementType"/>
 *         &lt;element name="operator">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Equals"/>
 *               &lt;enumeration value="Not Equals"/>
 *               &lt;enumeration value="Greater than"/>
 *               &lt;enumeration value="Greather than Or Equals"/>
 *               &lt;enumeration value="Less than"/>
 *               &lt;enumeration value="Less than or Equals"/>
 *               &lt;enumeration value="IN"/>
 *               &lt;enumeration value="Not IN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="multipleConditionJoinOperator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AND"/>
 *               &lt;enumeration value="OR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}filterConditionGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceDataElementRef",
    "operator",
    "expression",
    "multipleConditionJoinOperator",
    "filterConditionGroup"
})
@XmlRootElement(name = "conditionSpecification")
public class ConditionSpecification {

    @XmlElement(required = true)
    protected SourceDataElementType sourceDataElementRef;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String expression;
    protected String multipleConditionJoinOperator;
    protected FilterConditionGroup filterConditionGroup;

    /**
     * Gets the value of the sourceDataElementRef property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDataElementType }
     *     
     */
    public SourceDataElementType getSourceDataElementRef() {
        return sourceDataElementRef;
    }

    /**
     * Sets the value of the sourceDataElementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDataElementType }
     *     
     */
    public void setSourceDataElementRef(SourceDataElementType value) {
        this.sourceDataElementRef = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the multipleConditionJoinOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleConditionJoinOperator() {
        return multipleConditionJoinOperator;
    }

    /**
     * Sets the value of the multipleConditionJoinOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleConditionJoinOperator(String value) {
        this.multipleConditionJoinOperator = value;
    }

    /**
     * Optionally, a condition specification may consist of an inline condition group.
     * 
     * @return
     *     possible object is
     *     {@link FilterConditionGroup }
     *     
     */
    public FilterConditionGroup getFilterConditionGroup() {
        return filterConditionGroup;
    }

    /**
     * Sets the value of the filterConditionGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterConditionGroup }
     *     
     */
    public void setFilterConditionGroup(FilterConditionGroup value) {
        this.filterConditionGroup = value;
    }

}