
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectorDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="functionalScope" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="functionalDescription" type="{}descriptionType"/>
 *         &lt;element name="designDecision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connectorDefinition",
    "functionalScope",
    "functionalDescription",
    "designDecision"
})
@XmlRootElement(name = "connectorLogicDocumentation")
public class ConnectorLogicDocumentation {

    @XmlElement(required = true)
    protected String connectorDefinition;
    protected String functionalScope;
    @XmlElement(required = true)
    protected String functionalDescription;
    protected String designDecision;

    /**
     * Gets the value of the connectorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectorDefinition() {
        return connectorDefinition;
    }

    /**
     * Sets the value of the connectorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectorDefinition(String value) {
        this.connectorDefinition = value;
    }

    /**
     * Gets the value of the functionalScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalScope() {
        return functionalScope;
    }

    /**
     * Sets the value of the functionalScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalScope(String value) {
        this.functionalScope = value;
    }

    /**
     * Gets the value of the functionalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalDescription() {
        return functionalDescription;
    }

    /**
     * Sets the value of the functionalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalDescription(String value) {
        this.functionalDescription = value;
    }

    /**
     * Gets the value of the designDecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignDecision() {
        return designDecision;
    }

    /**
     * Sets the value of the designDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignDecision(String value) {
        this.designDecision = value;
    }

}