
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}conditionSpecification" maxOccurs="unbounded"/>
 *         &lt;element name="multipleGroupJoinOperator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AND"/>
 *               &lt;enumeration value="OR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conditionSpecification",
    "multipleGroupJoinOperator"
})
@XmlRootElement(name = "filterConditionGroup")
public class FilterConditionGroup {

    @XmlElement(required = true)
    protected List<ConditionSpecification> conditionSpecification;
    protected String multipleGroupJoinOperator;

    /**
     * Groups conditions that need to be evaluated as a single condition for the filtering criteria.Gets the value of the conditionSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objeds of the following type(s) are allowed in the list
     * {@link ConditionSpecification }
     * 
     * 
     */
    public List<ConditionSpecification> getConditionSpecification() {
        if (conditionSpecification == null) {
            conditionSpecification = new ArrayList<ConditionSpecification>();
        }
        return this.conditionSpecification;
    }

    /**
     * Gets the value of the multipleGroupJoinOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleGroupJoinOperator() {
        return multipleGroupJoinOperator;
    }

    /**
     * Sets the value of the multipleGroupJoinOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleGroupJoinOperator(String value) {
        this.multipleGroupJoinOperator = value;
    }

}