
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dataSwitch.xml.connectorspecs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Codepage_QNAME = new QName("", "codepage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dataSwitch.xml.connectorspecs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link COBOLRecordDef }
     * 
     */
    public COBOLRecordDef createCOBOLRecordDef() {
        return new COBOLRecordDef();
    }

    /**
     * Create an instance of {@link Connector }
     * 
     */
    public Connector createConnector() {
        return new Connector();
    }

    /**
     * Create an instance of {@link TargetDataElementType }
     * 
     */
    public TargetDataElementType createTargetDataElementType() {
        return new TargetDataElementType();
    }

    /**
     * Create an instance of {@link TargetDataElementType.TransformationRule }
     * 
     */
    public TargetDataElementType.TransformationRule createTargetDataElementTypeTransformationRule() {
        return new TargetDataElementType.TransformationRule();
    }

    /**
     * Create an instance of {@link XmlDocumentType }
     * 
     */
    public XmlDocumentType createXmlDocumentType() {
        return new XmlDocumentType();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element }
     * 
     */
    public XmlDocumentType.Element createXmlDocumentTypeElement() {
        return new XmlDocumentType.Element();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element.Content }
     * 
     */
    public XmlDocumentType.Element.Content createXmlDocumentTypeElementContent() {
        return new XmlDocumentType.Element.Content();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element.Content.OwnedElements }
     * 
     */
    public XmlDocumentType.Element.Content.OwnedElements createXmlDocumentTypeElementContentOwnedElements() {
        return new XmlDocumentType.Element.Content.OwnedElements();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element.Attributes }
     * 
     */
    public XmlDocumentType.Element.Attributes createXmlDocumentTypeElementAttributes() {
        return new XmlDocumentType.Element.Attributes();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds }
     * 
     */
    public Connector.ConnectionObjeds createConnectorConnectionObjeds() {
        return new Connector.ConnectionObjeds();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject createConnectorConnectionObjedsConnectionObject() {
        return new Connector.ConnectionObjeds.ConnectionObject();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.WebServices }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.WebServices createConnectorConnectionObjedsConnectionObjectWebServices() {
        return new Connector.ConnectionObjeds.ConnectionObject.WebServices();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture createConnectorConnectionObjedsConnectionObjectChangeDataCapture() {
        return new Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC createConnectorConnectionObjedsConnectionObjectChangeDataCaptureDb2CDC() {
        return new Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.Hadoop }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.Hadoop createConnectorConnectionObjedsConnectionObjectHadoop() {
        return new Connector.ConnectionObjeds.ConnectionObject.Hadoop();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive createConnectorConnectionObjedsConnectionObjectHadoopHive() {
        return new Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.FtpConnection }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.FtpConnection createConnectorConnectionObjedsConnectionObjectFtpConnection() {
        return new Connector.ConnectionObjeds.ConnectionObject.FtpConnection();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection createConnectorConnectionObjedsConnectionObjectDatabaseConnection() {
        return new Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows }
     * 
     */
    public Connector.ProcessFlows createConnectorProcessFlows() {
        return new Connector.ProcessFlows();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow createConnectorProcessFlowsProcessFlow() {
        return new Connector.ProcessFlows.ProcessFlow();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps createConnectorProcessFlowsProcessFlowSteps() {
        return new Connector.ProcessFlows.ProcessFlow.Steps();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step createConnectorProcessFlowsProcessFlowStepsStep() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask createConnectorProcessFlowsProcessFlowStepsStepOtherTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask createConnectorProcessFlowsProcessFlowStepsStepAssignmentTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask createConnectorProcessFlowsProcessFlowStepsStepCommandTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad createConnectorProcessFlowsProcessFlowStepsStepDataLoad() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps createConnectorProcessFlowsProcessFlowStepsStepNextSteps() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps createConnectorProcessFlowsProcessFlowStepsStepPreviousSteps() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution createConnectorProcessFlowsProcessFlowExecution() {
        return new Connector.ProcessFlows.ProcessFlow.Execution();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule createConnectorProcessFlowsProcessFlowExecutionSchedule() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler createConnectorProcessFlowsProcessFlowExecutionScheduleBuiltInScheduler() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables createConnectorProcessFlowsProcessFlowProcessFlowVariables() {
        return new Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables();
    }

    /**
     * Create an instance of {@link Connector.DataMappings }
     * 
     */
    public Connector.DataMappings createConnectorDataMappings() {
        return new Connector.DataMappings();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping }
     * 
     */
    public Connector.DataMappings.DataMapping createConnectorDataMappingsDataMapping() {
        return new Connector.DataMappings.DataMapping();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations createConnectorDataMappingsDataMappingDataTransformations() {
        return new Connector.DataMappings.DataMapping.DataTransformations();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation createConnectorDataMappingsDataMappingDataTransformationsDataTransformation() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate createConnectorDataMappingsDataMappingDataTransformationsDataTransformationRemoveDuplicate() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSorter() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank createConnectorDataMappingsDataMappingDataTransformationsDataTransformationRank() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSetOperation() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSetOperationInputGroups() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation createConnectorDataMappingsDataMappingDataTransformationsDataTransformationOtherTransformation() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements createConnectorDataMappingsDataMappingDataTransformationsDataTransformationOtherTransformationOutputDataElements() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements createConnectorDataMappingsDataMappingDataTransformationsDataTransformationOtherTransformationInputDataElements() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedure() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureOutputDataElements() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureInputDataElements() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureParameters() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner createConnectorDataMappingsDataMappingDataTransformationsDataTransformationMultijoiner() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent createConnectorDataMappingsDataMappingDataTransformationsDataTransformationMultijoinerDetailComponent() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationMultijoinerDetailComponentJoinCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner createConnectorDataMappingsDataMappingDataTransformationsDataTransformationJoiner() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationJoinerJoinCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping createConnectorDataMappingsDataMappingDataTransformationsDataTransformationConditionalGrouping() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookup() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupLookupSource() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupLookupSourceLookupCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupLookupSourceLookupConditionJoinCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset createConnectorDataMappingsDataMappingDataTransformationsDataTransformationTargetDataset() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDataset() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetSourceFeedJoin() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetSqlAliasElements() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetAssociatedSources() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataMappingVariables }
     * 
     */
    public Connector.DataMappings.DataMapping.DataMappingVariables createConnectorDataMappingsDataMappingDataMappingVariables() {
        return new Connector.DataMappings.DataMapping.DataMappingVariables();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.AdditionalProperties }
     * 
     */
    public Connector.DataMappings.DataMapping.AdditionalProperties createConnectorDataMappingsDataMappingAdditionalProperties() {
        return new Connector.DataMappings.DataMapping.AdditionalProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs }
     * 
     */
    public Connector.SystemCatalogs createConnectorSystemCatalogs() {
        return new Connector.SystemCatalogs();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog createConnectorSystemCatalogsSystemCatalog() {
        return new Connector.SystemCatalogs.SystemCatalog();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities createConnectorSystemCatalogsSystemCatalogSystemEntities() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntity() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityNonRelationalRecords() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityRelationalDataElements() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFileProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.SemiStructuredFileProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.SemiStructuredFileProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesSemiStructuredFileProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.SemiStructuredFileProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesFixedWidthProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesRelationalDatabaseProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties();
    }

    /**
     * Create an instance of {@link FilterConditionGroup }
     * 
     */
    public FilterConditionGroup createFilterConditionGroup() {
        return new FilterConditionGroup();
    }

    /**
     * Create an instance of {@link ConditionSpecification }
     * 
     */
    public ConditionSpecification createConditionSpecification() {
        return new ConditionSpecification();
    }

    /**
     * Create an instance of {@link SourceDataElementType }
     * 
     */
    public SourceDataElementType createSourceDataElementType() {
        return new SourceDataElementType();
    }

    /**
     * Create an instance of {@link ConnectorLogicDocumentation }
     * 
     */
    public ConnectorLogicDocumentation createConnectorLogicDocumentation() {
        return new ConnectorLogicDocumentation();
    }

    /**
     * Create an instance of {@link DataObjectDocumentation }
     * 
     */
    public DataObjectDocumentation createDataObjectDocumentation() {
        return new DataObjectDocumentation();
    }

    /**
     * Create an instance of {@link PrePostCommand }
     * 
     */
    public PrePostCommand createPrePostCommand() {
        return new PrePostCommand();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link COBOLRecordDef.Group }
     * 
     */
    public COBOLRecordDef.Group createCOBOLRecordDefGroup() {
        return new COBOLRecordDef.Group();
    }

    /**
     * Create an instance of {@link ContactPersonType }
     * 
     */
    public ContactPersonType createContactPersonType() {
        return new ContactPersonType();
    }

    /**
     * Create an instance of {@link PrePostVariableAssignment }
     * 
     */
    public PrePostVariableAssignment createPrePostVariableAssignment() {
        return new PrePostVariableAssignment();
    }

    /**
     * Create an instance of {@link InterimDataElementType }
     * 
     */
    public InterimDataElementType createInterimDataElementType() {
        return new InterimDataElementType();
    }

    /**
     * Create an instance of {@link InputDataElementType }
     * 
     */
    public InputDataElementType createInputDataElementType() {
        return new InputDataElementType();
    }

    /**
     * Create an instance of {@link DesignObjectDocumentationType }
     * 
     */
    public DesignObjectDocumentationType createDesignObjectDocumentationType() {
        return new DesignObjectDocumentationType();
    }

    /**
     * Create an instance of {@link TargetDataElementType.TransformationRule.Parameter }
     * 
     */
    public TargetDataElementType.TransformationRule.Parameter createTargetDataElementTypeTransformationRuleParameter() {
        return new TargetDataElementType.TransformationRule.Parameter();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef }
     * 
     */
    public XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef createXmlDocumentTypeElementContentOwnedElementsOwnedElementRef() {
        return new XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef();
    }

    /**
     * Create an instance of {@link XmlDocumentType.Element.Attributes.Attribute }
     * 
     */
    public XmlDocumentType.Element.Attributes.Attribute createXmlDocumentTypeElementAttributesAttribute() {
        return new XmlDocumentType.Element.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.SapKernel }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.SapKernel createConnectorConnectionObjedsConnectionObjectSapKernel() {
        return new Connector.ConnectionObjeds.ConnectionObject.SapKernel();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.JNDIApplication }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.JNDIApplication createConnectorConnectionObjedsConnectionObjectJNDIApplication() {
        return new Connector.ConnectionObjeds.ConnectionObject.JNDIApplication();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.JMSApplication }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.JMSApplication createConnectorConnectionObjedsConnectionObjectJMSApplication() {
        return new Connector.ConnectionObjeds.ConnectionObject.JMSApplication();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.MessageQueue }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.MessageQueue createConnectorConnectionObjedsConnectionObjectMessageQueue() {
        return new Connector.ConnectionObjeds.ConnectionObject.MessageQueue();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.WebServices.TrustCertificatesFile }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.WebServices.TrustCertificatesFile createConnectorConnectionObjedsConnectionObjectWebServicesTrustCertificatesFile() {
        return new Connector.ConnectionObjeds.ConnectionObject.WebServices.TrustCertificatesFile();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.WebServices.CertificateFile }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.WebServices.CertificateFile createConnectorConnectionObjedsConnectionObjectWebServicesCertificateFile() {
        return new Connector.ConnectionObjeds.ConnectionObject.WebServices.CertificateFile();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.WebServices.PrivateKeyFile }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.WebServices.PrivateKeyFile createConnectorConnectionObjedsConnectionObjectWebServicesPrivateKeyFile() {
        return new Connector.ConnectionObjeds.ConnectionObject.WebServices.PrivateKeyFile();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.OracleCDC }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.OracleCDC createConnectorConnectionObjedsConnectionObjectChangeDataCaptureOracleCDC() {
        return new Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.OracleCDC();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC.CaptureCatalogTable }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC.CaptureCatalogTable createConnectorConnectionObjedsConnectionObjectChangeDataCaptureDb2CDCCaptureCatalogTable() {
        return new Connector.ConnectionObjeds.ConnectionObject.ChangeDataCapture.Db2CDC.CaptureCatalogTable();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive.AdditionalConnectionParameter }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive.AdditionalConnectionParameter createConnectorConnectionObjedsConnectionObjectHadoopHiveAdditionalConnectionParameter() {
        return new Connector.ConnectionObjeds.ConnectionObject.Hadoop.Hive.AdditionalConnectionParameter();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.FtpConnection.SFTP }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.FtpConnection.SFTP createConnectorConnectionObjedsConnectionObjectFtpConnectionSFTP() {
        return new Connector.ConnectionObjeds.ConnectionObject.FtpConnection.SFTP();
    }

    /**
     * Create an instance of {@link Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection.AdditionalConnectionParameter }
     * 
     */
    public Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection.AdditionalConnectionParameter createConnectorConnectionObjedsConnectionObjectDatabaseConnectionAdditionalConnectionParameter() {
        return new Connector.ConnectionObjeds.ConnectionObject.DatabaseConnection.AdditionalConnectionParameter();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.ProcessFlowProperties }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.ProcessFlowProperties createConnectorProcessFlowsProcessFlowProcessFlowProperties() {
        return new Connector.ProcessFlows.ProcessFlow.ProcessFlowProperties();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.EventWait }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.EventWait createConnectorProcessFlowsProcessFlowStepsStepEventWait() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.EventWait();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.EventRaise }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.EventRaise createConnectorProcessFlowsProcessFlowStepsStepEventRaise() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.EventRaise();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.DecisionTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.DecisionTask createConnectorProcessFlowsProcessFlowStepsStepDecisionTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.DecisionTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.EmailTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.EmailTask createConnectorProcessFlowsProcessFlowStepsStepEmailTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.EmailTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.SequenceTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.SequenceTask createConnectorProcessFlowsProcessFlowStepsStepSequenceTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.SequenceTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.FilterTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.FilterTask createConnectorProcessFlowsProcessFlowStepsStepFilterTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.FilterTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.ControlTask }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.ControlTask createConnectorProcessFlowsProcessFlowStepsStepControlTask() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.ControlTask();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask.Parameter }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask.Parameter createConnectorProcessFlowsProcessFlowStepsStepOtherTaskParameter() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.OtherTask.Parameter();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask.VariableAssignment }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask.VariableAssignment createConnectorProcessFlowsProcessFlowStepsStepAssignmentTaskVariableAssignment() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.AssignmentTask.VariableAssignment();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask.Command }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask.Command createConnectorProcessFlowsProcessFlowStepsStepCommandTaskCommand() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.CommandTask.Command();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad.StepPrePostProcessing }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad.StepPrePostProcessing createConnectorProcessFlowsProcessFlowStepsStepDataLoadStepPrePostProcessing() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.DataLoad.StepPrePostProcessing();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps.NextStep }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps.NextStep createConnectorProcessFlowsProcessFlowStepsStepNextStepsNextStep() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.NextSteps.NextStep();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps.PreviousStep }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps.PreviousStep createConnectorProcessFlowsProcessFlowStepsStepPreviousStepsPreviousStep() {
        return new Connector.ProcessFlows.ProcessFlow.Steps.Step.PreviousSteps.PreviousStep();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule.ExternalScheduler }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule.ExternalScheduler createConnectorProcessFlowsProcessFlowExecutionScheduleExternalScheduler() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule.ExternalScheduler();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleStart }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleStart createConnectorProcessFlowsProcessFlowExecutionScheduleBuiltInSchedulerScheduleStart() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleStart();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleEnd }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleEnd createConnectorProcessFlowsProcessFlowExecutionScheduleBuiltInSchedulerScheduleEnd() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.ScheduleEnd();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.CustomRecurringSchedule }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.CustomRecurringSchedule createConnectorProcessFlowsProcessFlowExecutionScheduleBuiltInSchedulerCustomRecurringSchedule() {
        return new Connector.ProcessFlows.ProcessFlow.Execution.Schedule.BuiltInScheduler.CustomRecurringSchedule();
    }

    /**
     * Create an instance of {@link Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables.ProcessFlowVariable }
     * 
     */
    public Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables.ProcessFlowVariable createConnectorProcessFlowsProcessFlowProcessFlowVariablesProcessFlowVariable() {
        return new Connector.ProcessFlows.ProcessFlow.ProcessFlowVariables.ProcessFlowVariable();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.TargetDataElements }
     * 
     */
    public Connector.DataMappings.DataMapping.TargetDataElements createConnectorDataMappingsDataMappingTargetDataElements() {
        return new Connector.DataMappings.DataMapping.TargetDataElements();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.ExceptionHandling }
     * 
     */
    public Connector.DataMappings.DataMapping.ExceptionHandling createConnectorDataMappingsDataMappingExceptionHandling() {
        return new Connector.DataMappings.DataMapping.ExceptionHandling();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Filter }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Filter createConnectorDataMappingsDataMappingDataTransformationsDataTransformationFilter() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Filter();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Expression }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Expression createConnectorDataMappingsDataMappingDataTransformationsDataTransformationExpression() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Expression();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Aggregator }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Aggregator createConnectorDataMappingsDataMappingDataTransformationsDataTransformationAggregator() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Aggregator();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SequenceGenerator }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SequenceGenerator createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSequenceGenerator() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SequenceGenerator();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate.KeyColumn }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate.KeyColumn createConnectorDataMappingsDataMappingDataTransformationsDataTransformationRemoveDuplicateKeyColumn() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.RemoveDuplicate.KeyColumn();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter.SorterKey }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter.SorterKey createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSorterSorterKey() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Sorter.SorterKey();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.RankElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.RankElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationRankRankElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.RankElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.GroupByElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.GroupByElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationRankGroupByElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Rank.GroupByElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups.InputGroup }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups.InputGroup createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSetOperationInputGroupsInputGroup() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SetOperation.InputGroups.InputGroup();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements.OutputDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements.OutputDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationOtherTransformationOutputDataElementsOutputDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.OutputDataElements.OutputDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements.InputDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements.InputDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationOtherTransformationInputDataElementsInputDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.OtherTransformation.InputDataElements.InputDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Connection }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Connection createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureConnection() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Connection();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements.OutputDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements.OutputDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureOutputDataElementsOutputDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.OutputDataElements.OutputDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements.InputDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements.InputDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureInputDataElementsInputDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.InputDataElements.InputDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters.Parameter }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters.Parameter createConnectorDataMappingsDataMappingDataTransformationsDataTransformationStoredProcedureParametersParameter() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.StoredProcedure.Parameters.Parameter();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.MasterDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.MasterDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationMultijoinerDetailComponentJoinConditionMasterDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.MasterDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.DetailDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.DetailDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationMultijoinerDetailComponentJoinConditionDetailDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Multijoiner.DetailComponent.JoinCondition.DetailDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.MasterDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.MasterDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationJoinerJoinConditionMasterDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.MasterDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.DetailDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.DetailDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationJoinerJoinConditionDetailDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Joiner.JoinCondition.DetailDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping.OutputGroup }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping.OutputGroup createConnectorDataMappingsDataMappingDataTransformationsDataTransformationConditionalGroupingOutputGroup() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.ConditionalGrouping.OutputGroup();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.ReturnDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.ReturnDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupReturnDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.ReturnDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.InputDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.InputDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupLookupSourceLookupConditionJoinConditionInputDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.InputDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.LookupDataElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.LookupDataElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationLookupLookupSourceLookupConditionJoinConditionLookupDataElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.Lookup.LookupSource.LookupCondition.JoinCondition.LookupDataElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset.TargetDataLoadOptions }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset.TargetDataLoadOptions createConnectorDataMappingsDataMappingDataTransformationsDataTransformationTargetDatasetTargetDataLoadOptions() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.TargetDataset.TargetDataLoadOptions();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.FilterCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.FilterCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetFilterCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.FilterCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin.JoinCondition }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin.JoinCondition createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetSourceFeedJoinJoinCondition() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SourceFeedJoin.JoinCondition();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements.SqlAliasElement }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements.SqlAliasElement createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetSqlAliasElementsSqlAliasElement() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.SqlAliasElements.SqlAliasElement();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources.Source }
     * 
     */
    public Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources.Source createConnectorDataMappingsDataMappingDataTransformationsDataTransformationSourceDatasetAssociatedSourcesSource() {
        return new Connector.DataMappings.DataMapping.DataTransformations.DataTransformation.SourceDataset.AssociatedSources.Source();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.DataMappingVariables.DataMappingVariable }
     * 
     */
    public Connector.DataMappings.DataMapping.DataMappingVariables.DataMappingVariable createConnectorDataMappingsDataMappingDataMappingVariablesDataMappingVariable() {
        return new Connector.DataMappings.DataMapping.DataMappingVariables.DataMappingVariable();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.AdditionalProperties.Datastage }
     * 
     */
    public Connector.DataMappings.DataMapping.AdditionalProperties.Datastage createConnectorDataMappingsDataMappingAdditionalPropertiesDatastage() {
        return new Connector.DataMappings.DataMapping.AdditionalProperties.Datastage();
    }

    /**
     * Create an instance of {@link Connector.DataMappings.DataMapping.AdditionalProperties.Odi }
     * 
     */
    public Connector.DataMappings.DataMapping.AdditionalProperties.Odi createConnectorDataMappingsDataMappingAdditionalPropertiesOdi() {
        return new Connector.DataMappings.DataMapping.AdditionalProperties.Odi();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemConnection }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemConnection createConnectorSystemCatalogsSystemCatalogSystemConnection() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemConnection();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords.Record }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords.Record createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityNonRelationalRecordsRecord() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.NonRelationalRecords.Record();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements.DataElement }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements.DataElement createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityRelationalDataElementsDataElement() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.RelationalDataElements.DataElement();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ExcelFileProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ExcelFileProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesExcelFileProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ExcelFileProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ApplicationDatasetProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ApplicationDatasetProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesApplicationDatasetProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.ApplicationDatasetProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.HeaderRecord }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.HeaderRecord createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesHeaderRecord() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.HeaderRecord();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.DelimitedFileProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.DelimitedFileProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesDelimitedFileProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.DelimitedFileProperties();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.SemiStructuredFileProperties.NewRecordMarkers }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.SemiStructuredFileProperties.NewRecordMarkers createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesSemiStructuredFilePropertiesNewRecordMarkers() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.SemiStructuredFileProperties.NewRecordMarkers();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties.NullCharacter }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties.NullCharacter createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesFlatFilePropertiesFixedWidthPropertiesNullCharacter() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.FlatFileProperties.FixedWidthProperties.NullCharacter();
    }

    /**
     * Create an instance of {@link Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties.ViewProperties }
     * 
     */
    public Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties.ViewProperties createConnectorSystemCatalogsSystemCatalogSystemEntitiesSystemEntityPhysicalPropertiesRelationalDatabasePropertiesViewProperties() {
        return new Connector.SystemCatalogs.SystemCatalog.SystemEntities.SystemEntity.PhysicalProperties.RelationalDatabaseProperties.ViewProperties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codepage")
    public JAXBElement<String> createCodepage(String value) {
        return new JAXBElement<String>(_Codepage_QNAME, String.class, null, value);
    }

}