
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Global element type used to specify named reference
 * 				to the entity data element including the system entity reference.
 * 			
 * 
 * <p>Java class for sourceDataElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sourceDataElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sourceFeedRef" use="required" type="{}nameType" />
 *       &lt;attribute name="sourceDataElementRef" use="required" type="{}nameType" />
 *       &lt;attribute name="alias" type="{}nameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sourceDataElementType")
public class SourceDataElementType {

    @XmlAttribute(name = "sourceFeedRef", required = true)
    protected String sourceFeedRef;
    @XmlAttribute(name = "sourceDataElementRef", required = true)
    protected String sourceDataElementRef;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the sourceFeedRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceFeedRef() {
        return sourceFeedRef;
    }

    /**
     * Sets the value of the sourceFeedRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceFeedRef(String value) {
        this.sourceFeedRef = value;
    }

    /**
     * Gets the value of the sourceDataElementRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDataElementRef() {
        return sourceDataElementRef;
    }

    /**
     * Sets the value of the sourceDataElementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDataElementRef(String value) {
        this.sourceDataElementRef = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}