
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides formal specification of the data mapping for each data element. 
 * 
 * <p>Java class for targetDataElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="targetDataElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="directSourceDataElementRef" type="{}sourceDataElementType" minOccurs="0"/>
 *         &lt;element name="transformationRule" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="specialProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{}businessNameType">
 *                                 &lt;enumeration value="Anchoring Component Name"/>
 *                                 &lt;enumeration value="Case Sensitivity Flag"/>
 *                                 &lt;enumeration value="Code Value"/>
 *                                 &lt;enumeration value="Condition"/>
 *                                 &lt;enumeration value="Condition SQL"/>
 *                                 &lt;enumeration value="Constant Value"/>
 *                                 &lt;enumeration value="Database Type"/>
 *                                 &lt;enumeration value="Date Format"/>
 *                                 &lt;enumeration value="Input Date Format"/>
 *                                 &lt;enumeration value="Output Date Format"/>
 *                                 &lt;enumeration value="Date Part"/>
 *                                 &lt;enumeration value="Decoded Value"/>
 *                                 &lt;enumeration value="Expression"/>
 *                                 &lt;enumeration value="File Path"/>
 *                                 &lt;enumeration value="Group By"/>
 *                                 &lt;enumeration value="Input Data Element Name"/>
 *                                 &lt;enumeration value="Key"/>
 *                                 &lt;enumeration value="Lower Threshold Value"/>
 *                                 &lt;enumeration value="New String"/>
 *                                 &lt;enumeration value="Number of Characters"/>
 *                                 &lt;enumeration value="Number of Occurrence"/>
 *                                 &lt;enumeration value="Old String"/>
 *                                 &lt;enumeration value="Output Data Element Name"/>
 *                                 &lt;enumeration value="Padding String"/>
 *                                 &lt;enumeration value="Precision"/>
 *                                 &lt;enumeration value="Rank Number"/>
 *                                 &lt;enumeration value="Rank Port"/>
 *                                 &lt;enumeration value="Return Data Element"/>
 *                                 &lt;enumeration value="Return Value If False"/>
 *                                 &lt;enumeration value="Return Value If True"/>
 *                                 &lt;enumeration value="Rowset Count"/>
 *                                 &lt;enumeration value="Search Value"/>
 *                                 &lt;enumeration value="Sort Order"/>
 *                                 &lt;enumeration value="Sorted Input"/>
 *                                 &lt;enumeration value="SQL Query"/>
 *                                 &lt;enumeration value="Starting Position"/>
 *                                 &lt;enumeration value="Starting Value"/>
 *                                 &lt;enumeration value="Suppress NULLs"/>
 *                                 &lt;enumeration value="Timestamp Format"/>
 *                                 &lt;enumeration value="Top / Bottom Flag"/>
 *                                 &lt;enumeration value="Transformation Name"/>
 *                                 &lt;enumeration value="Transformation Type"/>
 *                                 &lt;enumeration value="Upper Threshold Value"/>
 *                                 &lt;enumeration value="Use Distinct"/>
 *                                 &lt;enumeration value="var"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="type" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{}businessNameType">
 *                                 &lt;enumeration value="SC"/>
 *                                 &lt;enumeration value="NC"/>
 *                                 &lt;enumeration value="DE"/>
 *                                 &lt;enumeration value="Exp"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ruleName" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{}businessNameType">
 *                       &lt;enumeration value="Direct Mapping"/>
 *                       &lt;enumeration value="Aggregate - Average"/>
 *                       &lt;enumeration value="Aggregate - Count"/>
 *                       &lt;enumeration value="Aggregate - First"/>
 *                       &lt;enumeration value="Aggregate - Last"/>
 *                       &lt;enumeration value="Aggregate - Maximum"/>
 *                       &lt;enumeration value="Aggregate - Minimum"/>
 *                       &lt;enumeration value="Aggregate - Sum"/>
 *                       &lt;enumeration value="String - Return ASCII Code"/>
 *                       &lt;enumeration value="String - Return ASCII Character"/>
 *                       &lt;enumeration value="String - Convert to Lowercase"/>
 *                       &lt;enumeration value="String - Convert to Uppercase"/>
 *                       &lt;enumeration value="String - Convert to InitCaps"/>
 *                       &lt;enumeration value="String - Length"/>
 *                       &lt;enumeration value="String - Concatenation"/>
 *                       &lt;enumeration value="String - Substring"/>
 *                       &lt;enumeration value="String - Trim Leading Spaces"/>
 *                       &lt;enumeration value="String - Trim Trailing Spaces"/>
 *                       &lt;enumeration value="String - Trim Leading and Trailing Spaces"/>
 *                       &lt;enumeration value="String - Left Padding"/>
 *                       &lt;enumeration value="String - Right Padding"/>
 *                       &lt;enumeration value="String - Search String"/>
 *                       &lt;enumeration value="String - Replace String"/>
 *                       &lt;enumeration value="String - Reverse"/>
 *                       &lt;enumeration value="Numeric - Absolute"/>
 *                       &lt;enumeration value="Numeric - Ceil"/>
 *                       &lt;enumeration value="Numeric - Floor"/>
 *                       &lt;enumeration value="Numeric - Cumulative Total"/>
 *                       &lt;enumeration value="Numeric - Moving Sum"/>
 *                       &lt;enumeration value="Numeric - Moving Average"/>
 *                       &lt;enumeration value="Numeric - Round"/>
 *                       &lt;enumeration value="Numeric - Truncate"/>
 *                       &lt;enumeration value="Date/Time - Add to Date"/>
 *                       &lt;enumeration value="Date/Time - Difference between Dates"/>
 *                       &lt;enumeration value="Date/Time - Get Date/Time Part"/>
 *                       &lt;enumeration value="Date/Time - Truncate"/>
 *                       &lt;enumeration value="Date/Time - Round"/>
 *                       &lt;enumeration value="Conversion - String to Date"/>
 *                       &lt;enumeration value="Conversion - Date to String"/>
 *                       &lt;enumeration value="Conversion - Date Format"/>
 *                       &lt;enumeration value="Conversion - String to Integer"/>
 *                       &lt;enumeration value="Conversion - String to Decimal"/>
 *                       &lt;enumeration value="Conversion - String to Float"/>
 *                       &lt;enumeration value="Conversion - Numeric to String"/>
 *                       &lt;enumeration value="Conversion - Date/Time to String"/>
 *                       &lt;enumeration value="Conversion - Date/Time to Integer"/>
 *                       &lt;enumeration value="Encoding - AES Encryption"/>
 *                       &lt;enumeration value="Encoding - AES Decryption"/>
 *                       &lt;enumeration value="Encoding - MD5 Checksum"/>
 *                       &lt;enumeration value="Encoding - CRC32"/>
 *                       &lt;enumeration value="General - Expression"/>
 *                       &lt;enumeration value="General - Constant Value"/>
 *                       &lt;enumeration value="Check - NULL Values"/>
 *                       &lt;enumeration value="Check - Date Values"/>
 *                       &lt;enumeration value="Check - Numeric Values"/>
 *                       &lt;enumeration value="Check - Condition"/>
 *                       &lt;enumeration value="Check - Threshold Values"/>
 *                       &lt;enumeration value="Lookup"/>
 *                       &lt;enumeration value="Special - Union"/>
 *                       &lt;enumeration value="Special - Decode"/>
 *                       &lt;enumeration value="Special - Surrogate Key Generation"/>
 *                       &lt;enumeration value="Special - Sequence Generator"/>
 *                       &lt;enumeration value="Special - Rank Index"/>
 *                       &lt;enumeration value="Audit / Generated - System Date"/>
 *                       &lt;enumeration value="Audit / Generated - System Timestamp"/>
 *                       &lt;enumeration value="Audit - Oracle CDC - UOW"/>
 *                       &lt;enumeration value="Audit - Oracle CDC - UOW Row Number"/>
 *                       &lt;enumeration value="Audit - Oracle CDC - Change Type"/>
 *                       &lt;enumeration value="Audit - Oracle CDC - Change Timestamp"/>
 *                       &lt;enumeration value="Other Transformation"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="componentName" type="{}nameType" />
 *                 &lt;attribute name="prevComponentName" type="{}nameType" />
 *                 &lt;attribute name="tempElemName" type="{}nameType" />
 *                 &lt;attribute name="originalExpression" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="errorDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="description" type="{}descriptionType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="targetDatsetRef" use="required" type="{}nameType" />
 *       &lt;attribute name="targetDataElementRef" use="required" type="{}nameType" />
 *       &lt;attribute name="dataType" type="{}nameType" />
 *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "targetDataElementType", propOrder = {
    "directSourceDataElementRef",
    "transformationRule"
})
public class TargetDataElementType {

    protected SourceDataElementType directSourceDataElementRef;
    protected List<TargetDataElementType.TransformationRule> transformationRule;
    @XmlAttribute(name = "targetDatsetRef", required = true)
    protected String targetDatsetRef;
    @XmlAttribute(name = "targetDataElementRef", required = true)
    protected String targetDataElementRef;
    @XmlAttribute(name = "dataType")
    protected String dataType;
    @XmlAttribute(name = "precision")
    protected Integer precision;
    @XmlAttribute(name = "scale")
    protected Integer scale;

    /**
     * Gets the value of the directSourceDataElementRef property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDataElementType }
     *     
     */
    public SourceDataElementType getDirectSourceDataElementRef() {
        return directSourceDataElementRef;
    }

    /**
     * Sets the value of the directSourceDataElementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDataElementType }
     *     
     */
    public void setDirectSourceDataElementRef(SourceDataElementType value) {
        this.directSourceDataElementRef = value;
    }

    /**
     * Gets the value of the transformationRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformationRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformationRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objeds of the following type(s) are allowed in the list
     * {@link TargetDataElementType.TransformationRule }
     * 
     * 
     */
    public List<TargetDataElementType.TransformationRule> getTransformationRule() {
        if (transformationRule == null) {
            transformationRule = new ArrayList<TargetDataElementType.TransformationRule>();
        }
        return this.transformationRule;
    }

    /**
     * Gets the value of the targetDatsetRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDatsetRef() {
        return targetDatsetRef;
    }

    /**
     * Sets the value of the targetDatsetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDatsetRef(String value) {
        this.targetDatsetRef = value;
    }

    /**
     * Gets the value of the targetDataElementRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDataElementRef() {
        return targetDataElementRef;
    }

    /**
     * Sets the value of the targetDataElementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDataElementRef(String value) {
        this.targetDataElementRef = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecision(Integer value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScale(Integer value) {
        this.scale = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="specialProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{}businessNameType">
     *                       &lt;enumeration value="Anchoring Component Name"/>
     *                       &lt;enumeration value="Case Sensitivity Flag"/>
     *                       &lt;enumeration value="Code Value"/>
     *                       &lt;enumeration value="Condition"/>
     *                       &lt;enumeration value="Condition SQL"/>
     *                       &lt;enumeration value="Constant Value"/>
     *                       &lt;enumeration value="Database Type"/>
     *                       &lt;enumeration value="Date Format"/>
     *                       &lt;enumeration value="Input Date Format"/>
     *                       &lt;enumeration value="Output Date Format"/>
     *                       &lt;enumeration value="Date Part"/>
     *                       &lt;enumeration value="Decoded Value"/>
     *                       &lt;enumeration value="Expression"/>
     *                       &lt;enumeration value="File Path"/>
     *                       &lt;enumeration value="Group By"/>
     *                       &lt;enumeration value="Input Data Element Name"/>
     *                       &lt;enumeration value="Key"/>
     *                       &lt;enumeration value="Lower Threshold Value"/>
     *                       &lt;enumeration value="New String"/>
     *                       &lt;enumeration value="Number of Characters"/>
     *                       &lt;enumeration value="Number of Occurrence"/>
     *                       &lt;enumeration value="Old String"/>
     *                       &lt;enumeration value="Output Data Element Name"/>
     *                       &lt;enumeration value="Padding String"/>
     *                       &lt;enumeration value="Precision"/>
     *                       &lt;enumeration value="Rank Number"/>
     *                       &lt;enumeration value="Rank Port"/>
     *                       &lt;enumeration value="Return Data Element"/>
     *                       &lt;enumeration value="Return Value If False"/>
     *                       &lt;enumeration value="Return Value If True"/>
     *                       &lt;enumeration value="Rowset Count"/>
     *                       &lt;enumeration value="Search Value"/>
     *                       &lt;enumeration value="Sort Order"/>
     *                       &lt;enumeration value="Sorted Input"/>
     *                       &lt;enumeration value="SQL Query"/>
     *                       &lt;enumeration value="Starting Position"/>
     *                       &lt;enumeration value="Starting Value"/>
     *                       &lt;enumeration value="Suppress NULLs"/>
     *                       &lt;enumeration value="Timestamp Format"/>
     *                       &lt;enumeration value="Top / Bottom Flag"/>
     *                       &lt;enumeration value="Transformation Name"/>
     *                       &lt;enumeration value="Transformation Type"/>
     *                       &lt;enumeration value="Upper Threshold Value"/>
     *                       &lt;enumeration value="Use Distinct"/>
     *                       &lt;enumeration value="var"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="type" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{}businessNameType">
     *                       &lt;enumeration value="SC"/>
     *                       &lt;enumeration value="NC"/>
     *                       &lt;enumeration value="DE"/>
     *                       &lt;enumeration value="Exp"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ruleName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}businessNameType">
     *             &lt;enumeration value="Direct Mapping"/>
     *             &lt;enumeration value="Aggregate - Average"/>
     *             &lt;enumeration value="Aggregate - Count"/>
     *             &lt;enumeration value="Aggregate - First"/>
     *             &lt;enumeration value="Aggregate - Last"/>
     *             &lt;enumeration value="Aggregate - Maximum"/>
     *             &lt;enumeration value="Aggregate - Minimum"/>
     *             &lt;enumeration value="Aggregate - Sum"/>
     *             &lt;enumeration value="String - Return ASCII Code"/>
     *             &lt;enumeration value="String - Return ASCII Character"/>
     *             &lt;enumeration value="String - Convert to Lowercase"/>
     *             &lt;enumeration value="String - Convert to Uppercase"/>
     *             &lt;enumeration value="String - Convert to InitCaps"/>
     *             &lt;enumeration value="String - Length"/>
     *             &lt;enumeration value="String - Concatenation"/>
     *             &lt;enumeration value="String - Substring"/>
     *             &lt;enumeration value="String - Trim Leading Spaces"/>
     *             &lt;enumeration value="String - Trim Trailing Spaces"/>
     *             &lt;enumeration value="String - Trim Leading and Trailing Spaces"/>
     *             &lt;enumeration value="String - Left Padding"/>
     *             &lt;enumeration value="String - Right Padding"/>
     *             &lt;enumeration value="String - Search String"/>
     *             &lt;enumeration value="String - Replace String"/>
     *             &lt;enumeration value="String - Reverse"/>
     *             &lt;enumeration value="Numeric - Absolute"/>
     *             &lt;enumeration value="Numeric - Ceil"/>
     *             &lt;enumeration value="Numeric - Floor"/>
     *             &lt;enumeration value="Numeric - Cumulative Total"/>
     *             &lt;enumeration value="Numeric - Moving Sum"/>
     *             &lt;enumeration value="Numeric - Moving Average"/>
     *             &lt;enumeration value="Numeric - Round"/>
     *             &lt;enumeration value="Numeric - Truncate"/>
     *             &lt;enumeration value="Date/Time - Add to Date"/>
     *             &lt;enumeration value="Date/Time - Difference between Dates"/>
     *             &lt;enumeration value="Date/Time - Get Date/Time Part"/>
     *             &lt;enumeration value="Date/Time - Truncate"/>
     *             &lt;enumeration value="Date/Time - Round"/>
     *             &lt;enumeration value="Conversion - String to Date"/>
     *             &lt;enumeration value="Conversion - Date to String"/>
     *             &lt;enumeration value="Conversion - Date Format"/>
     *             &lt;enumeration value="Conversion - String to Integer"/>
     *             &lt;enumeration value="Conversion - String to Decimal"/>
     *             &lt;enumeration value="Conversion - String to Float"/>
     *             &lt;enumeration value="Conversion - Numeric to String"/>
     *             &lt;enumeration value="Conversion - Date/Time to String"/>
     *             &lt;enumeration value="Conversion - Date/Time to Integer"/>
     *             &lt;enumeration value="Encoding - AES Encryption"/>
     *             &lt;enumeration value="Encoding - AES Decryption"/>
     *             &lt;enumeration value="Encoding - MD5 Checksum"/>
     *             &lt;enumeration value="Encoding - CRC32"/>
     *             &lt;enumeration value="General - Expression"/>
     *             &lt;enumeration value="General - Constant Value"/>
     *             &lt;enumeration value="Check - NULL Values"/>
     *             &lt;enumeration value="Check - Date Values"/>
     *             &lt;enumeration value="Check - Numeric Values"/>
     *             &lt;enumeration value="Check - Condition"/>
     *             &lt;enumeration value="Check - Threshold Values"/>
     *             &lt;enumeration value="Lookup"/>
     *             &lt;enumeration value="Special - Union"/>
     *             &lt;enumeration value="Special - Decode"/>
     *             &lt;enumeration value="Special - Surrogate Key Generation"/>
     *             &lt;enumeration value="Special - Sequence Generator"/>
     *             &lt;enumeration value="Special - Rank Index"/>
     *             &lt;enumeration value="Audit / Generated - System Date"/>
     *             &lt;enumeration value="Audit / Generated - System Timestamp"/>
     *             &lt;enumeration value="Audit - Oracle CDC - UOW"/>
     *             &lt;enumeration value="Audit - Oracle CDC - UOW Row Number"/>
     *             &lt;enumeration value="Audit - Oracle CDC - Change Type"/>
     *             &lt;enumeration value="Audit - Oracle CDC - Change Timestamp"/>
     *             &lt;enumeration value="Other Transformation"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="componentName" type="{}nameType" />
     *       &lt;attribute name="prevComponentName" type="{}nameType" />
     *       &lt;attribute name="tempElemName" type="{}nameType" />
     *       &lt;attribute name="originalExpression" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="errorDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="description" type="{}descriptionType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specialProperties",
        "parameter"
    })
    public static class TransformationRule {

        protected String specialProperties;
        protected List<TargetDataElementType.TransformationRule.Parameter> parameter;
        @XmlAttribute(name = "ruleName", required = true)
        protected String ruleName;
        @XmlAttribute(name = "componentName")
        protected String componentName;
        @XmlAttribute(name = "prevComponentName")
        protected String prevComponentName;
        @XmlAttribute(name = "tempElemName")
        protected String tempElemName;
        @XmlAttribute(name = "originalExpression")
        protected String originalExpression;
        @XmlAttribute(name = "errorDetails")
        protected String errorDetails;
        @XmlAttribute(name = "description")
        protected String description;

        /**
         * Gets the value of the specialProperties property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecialProperties() {
            return specialProperties;
        }

        /**
         * Sets the value of the specialProperties property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecialProperties(String value) {
            this.specialProperties = value;
        }

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objeds of the following type(s) are allowed in the list
         * {@link TargetDataElementType.TransformationRule.Parameter }
         * 
         * 
         */
        public List<TargetDataElementType.TransformationRule.Parameter> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<TargetDataElementType.TransformationRule.Parameter>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the ruleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRuleName() {
            return ruleName;
        }

        /**
         * Sets the value of the ruleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRuleName(String value) {
            this.ruleName = value;
        }

        /**
         * Gets the value of the componentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComponentName() {
            return componentName;
        }

        /**
         * Sets the value of the componentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComponentName(String value) {
            this.componentName = value;
        }

        /**
         * Gets the value of the prevComponentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrevComponentName() {
            return prevComponentName;
        }

        /**
         * Sets the value of the prevComponentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrevComponentName(String value) {
            this.prevComponentName = value;
        }

        /**
         * Gets the value of the tempElemName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTempElemName() {
            return tempElemName;
        }

        /**
         * Sets the value of the tempElemName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTempElemName(String value) {
            this.tempElemName = value;
        }

        /**
         * Gets the value of the originalExpression property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalExpression() {
            return originalExpression;
        }

        /**
         * Sets the value of the originalExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalExpression(String value) {
            this.originalExpression = value;
        }

        /**
         * Gets the value of the errorDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorDetails() {
            return errorDetails;
        }

        /**
         * Sets the value of the errorDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorDetails(String value) {
            this.errorDetails = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{}businessNameType">
         *             &lt;enumeration value="Anchoring Component Name"/>
         *             &lt;enumeration value="Case Sensitivity Flag"/>
         *             &lt;enumeration value="Code Value"/>
         *             &lt;enumeration value="Condition"/>
         *             &lt;enumeration value="Condition SQL"/>
         *             &lt;enumeration value="Constant Value"/>
         *             &lt;enumeration value="Database Type"/>
         *             &lt;enumeration value="Date Format"/>
         *             &lt;enumeration value="Input Date Format"/>
         *             &lt;enumeration value="Output Date Format"/>
         *             &lt;enumeration value="Date Part"/>
         *             &lt;enumeration value="Decoded Value"/>
         *             &lt;enumeration value="Expression"/>
         *             &lt;enumeration value="File Path"/>
         *             &lt;enumeration value="Group By"/>
         *             &lt;enumeration value="Input Data Element Name"/>
         *             &lt;enumeration value="Key"/>
         *             &lt;enumeration value="Lower Threshold Value"/>
         *             &lt;enumeration value="New String"/>
         *             &lt;enumeration value="Number of Characters"/>
         *             &lt;enumeration value="Number of Occurrence"/>
         *             &lt;enumeration value="Old String"/>
         *             &lt;enumeration value="Output Data Element Name"/>
         *             &lt;enumeration value="Padding String"/>
         *             &lt;enumeration value="Precision"/>
         *             &lt;enumeration value="Rank Number"/>
         *             &lt;enumeration value="Rank Port"/>
         *             &lt;enumeration value="Return Data Element"/>
         *             &lt;enumeration value="Return Value If False"/>
         *             &lt;enumeration value="Return Value If True"/>
         *             &lt;enumeration value="Rowset Count"/>
         *             &lt;enumeration value="Search Value"/>
         *             &lt;enumeration value="Sort Order"/>
         *             &lt;enumeration value="Sorted Input"/>
         *             &lt;enumeration value="SQL Query"/>
         *             &lt;enumeration value="Starting Position"/>
         *             &lt;enumeration value="Starting Value"/>
         *             &lt;enumeration value="Suppress NULLs"/>
         *             &lt;enumeration value="Timestamp Format"/>
         *             &lt;enumeration value="Top / Bottom Flag"/>
         *             &lt;enumeration value="Transformation Name"/>
         *             &lt;enumeration value="Transformation Type"/>
         *             &lt;enumeration value="Upper Threshold Value"/>
         *             &lt;enumeration value="Use Distinct"/>
         *             &lt;enumeration value="var"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="type" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{}businessNameType">
         *             &lt;enumeration value="SC"/>
         *             &lt;enumeration value="NC"/>
         *             &lt;enumeration value="DE"/>
         *             &lt;enumeration value="Exp"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Parameter {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "type", required = true)
            protected String type;
            @XmlAttribute(name = "value", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}