
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.07 at 04:15:27 PM IST 
//


package com.dataSwitch.xml.connectorspecs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulates specification for XML Schema.
 * 
 * <p>Java class for xmlDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlDocumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="element" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attributes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attribute" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{}nameType" />
 *                                     &lt;attribute name="description" type="{}descriptionType" />
 *                                     &lt;attribute name="changeability">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="Changeable"/>
 *                                           &lt;enumeration value="Frozen"/>
 *                                           &lt;enumeration value="Add Only"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="attributeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ownedElements" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ownedElementRef" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="elementRef" use="required" type="{}nameType" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="contentType" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Empty"/>
 *                                 &lt;enumeration value="Any"/>
 *                                 &lt;enumeration value="Mixed"/>
 *                                 &lt;enumeration value="Element"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="occurrence" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="One"/>
 *                                 &lt;enumeration value="Zero or One"/>
 *                                 &lt;enumeration value="Zero or More"/>
 *                                 &lt;enumeration value="One or More"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="orderType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="elementTypeRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{}nameType" />
 *                 &lt;attribute name="description" type="{}descriptionType" />
 *                 &lt;attribute name="elementType" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="empty"/>
 *                       &lt;enumeration value="any"/>
 *                       &lt;enumeration value="mixed"/>
 *                       &lt;enumeration value="element"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="occurrence" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="One"/>
 *                       &lt;enumeration value="Zero or One"/>
 *                       &lt;enumeration value="Zero or More"/>
 *                       &lt;enumeration value="One or More"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="typeDefinition" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="xmlSchemaVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmlDocumentType", propOrder = {
    "element",
    "typeDefinition"
})
public class XmlDocumentType {

    @XmlElement(required = true)
    protected List<XmlDocumentType.Element> element;
    protected List<Object> typeDefinition;
    @XmlAttribute(name = "xmlSchemaVersion")
    protected String xmlSchemaVersion;
    @XmlAttribute(name = "xmlNamespace", required = true)
    protected String xmlNamespace;

    /**
     * Gets the value of the element property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the element property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objeds of the following type(s) are allowed in the list
     * {@link XmlDocumentType.Element }
     * 
     * 
     */
    public List<XmlDocumentType.Element> getElement() {
        if (element == null) {
            element = new ArrayList<XmlDocumentType.Element>();
        }
        return this.element;
    }

    /**
     * Gets the value of the typeDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objeds of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getTypeDefinition() {
        if (typeDefinition == null) {
            typeDefinition = new ArrayList<Object>();
        }
        return this.typeDefinition;
    }

    /**
     * Gets the value of the xmlSchemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlSchemaVersion() {
        return xmlSchemaVersion;
    }

    /**
     * Sets the value of the xmlSchemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlSchemaVersion(String value) {
        this.xmlSchemaVersion = value;
    }

    /**
     * Gets the value of the xmlNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlNamespace() {
        return xmlNamespace;
    }

    /**
     * Sets the value of the xmlNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlNamespace(String value) {
        this.xmlNamespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attributes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attribute" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{}nameType" />
     *                           &lt;attribute name="description" type="{}descriptionType" />
     *                           &lt;attribute name="changeability">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="Changeable"/>
     *                                 &lt;enumeration value="Frozen"/>
     *                                 &lt;enumeration value="Add Only"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="attributeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ownedElements" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ownedElementRef" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="elementRef" use="required" type="{}nameType" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="contentType" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Empty"/>
     *                       &lt;enumeration value="Any"/>
     *                       &lt;enumeration value="Mixed"/>
     *                       &lt;enumeration value="Element"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="occurrence" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="One"/>
     *                       &lt;enumeration value="Zero or One"/>
     *                       &lt;enumeration value="Zero or More"/>
     *                       &lt;enumeration value="One or More"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="orderType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="elementTypeRef" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{}nameType" />
     *       &lt;attribute name="description" type="{}descriptionType" />
     *       &lt;attribute name="elementType" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="empty"/>
     *             &lt;enumeration value="any"/>
     *             &lt;enumeration value="mixed"/>
     *             &lt;enumeration value="element"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="occurrence" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="One"/>
     *             &lt;enumeration value="Zero or One"/>
     *             &lt;enumeration value="Zero or More"/>
     *             &lt;enumeration value="One or More"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributes",
        "content"
    })
    public static class Element {

        protected XmlDocumentType.Element.Attributes attributes;
        protected List<XmlDocumentType.Element.Content> content;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "description")
        protected String description;
        @XmlAttribute(name = "elementType", required = true)
        protected String elementType;
        @XmlAttribute(name = "occurrence", required = true)
        protected String occurrence;
        @XmlAttribute(name = "xPath", required = true)
        protected String xPath;

        /**
         * Gets the value of the attributes property.
         * 
         * @return
         *     possible object is
         *     {@link XmlDocumentType.Element.Attributes }
         *     
         */
        public XmlDocumentType.Element.Attributes getAttributes() {
            return attributes;
        }

        /**
         * Sets the value of the attributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlDocumentType.Element.Attributes }
         *     
         */
        public void setAttributes(XmlDocumentType.Element.Attributes value) {
            this.attributes = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objeds of the following type(s) are allowed in the list
         * {@link XmlDocumentType.Element.Content }
         * 
         * 
         */
        public List<XmlDocumentType.Element.Content> getContent() {
            if (content == null) {
                content = new ArrayList<XmlDocumentType.Element.Content>();
            }
            return this.content;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the elementType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElementType() {
            return elementType;
        }

        /**
         * Sets the value of the elementType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElementType(String value) {
            this.elementType = value;
        }

        /**
         * Gets the value of the occurrence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOccurrence() {
            return occurrence;
        }

        /**
         * Sets the value of the occurrence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOccurrence(String value) {
            this.occurrence = value;
        }

        /**
         * Gets the value of the xPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXPath() {
            return xPath;
        }

        /**
         * Sets the value of the xPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXPath(String value) {
            this.xPath = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attribute" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{}nameType" />
         *                 &lt;attribute name="description" type="{}descriptionType" />
         *                 &lt;attribute name="changeability">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="Changeable"/>
         *                       &lt;enumeration value="Frozen"/>
         *                       &lt;enumeration value="Add Only"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="attributeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attribute"
        })
        public static class Attributes {

            @XmlElement(required = true)
            protected List<XmlDocumentType.Element.Attributes.Attribute> attribute;

            /**
             * Gets the value of the attribute property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attribute property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttribute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objeds of the following type(s) are allowed in the list
             * {@link XmlDocumentType.Element.Attributes.Attribute }
             * 
             * 
             */
            public List<XmlDocumentType.Element.Attributes.Attribute> getAttribute() {
                if (attribute == null) {
                    attribute = new ArrayList<XmlDocumentType.Element.Attributes.Attribute>();
                }
                return this.attribute;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{}nameType" />
             *       &lt;attribute name="description" type="{}descriptionType" />
             *       &lt;attribute name="changeability">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="Changeable"/>
             *             &lt;enumeration value="Frozen"/>
             *             &lt;enumeration value="Add Only"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="attributeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="xPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Attribute {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "description")
                protected String description;
                @XmlAttribute(name = "changeability")
                protected String changeability;
                @XmlAttribute(name = "attributeType", required = true)
                protected String attributeType;
                @XmlAttribute(name = "required", required = true)
                protected boolean required;
                @XmlAttribute(name = "length")
                protected Integer length;
                @XmlAttribute(name = "precision")
                protected Integer precision;
                @XmlAttribute(name = "scale")
                protected Integer scale;
                @XmlAttribute(name = "initialValue")
                @XmlSchemaType(name = "anySimpleType")
                protected String initialValue;
                @XmlAttribute(name = "xPath", required = true)
                protected String xPath;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the changeability property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChangeability() {
                    return changeability;
                }

                /**
                 * Sets the value of the changeability property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChangeability(String value) {
                    this.changeability = value;
                }

                /**
                 * Gets the value of the attributeType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAttributeType() {
                    return attributeType;
                }

                /**
                 * Sets the value of the attributeType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAttributeType(String value) {
                    this.attributeType = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 */
                public boolean isRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 */
                public void setRequired(boolean value) {
                    this.required = value;
                }

                /**
                 * Gets the value of the length property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getLength() {
                    return length;
                }

                /**
                 * Sets the value of the length property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setLength(Integer value) {
                    this.length = value;
                }

                /**
                 * Gets the value of the precision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getPrecision() {
                    return precision;
                }

                /**
                 * Sets the value of the precision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setPrecision(Integer value) {
                    this.precision = value;
                }

                /**
                 * Gets the value of the scale property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getScale() {
                    return scale;
                }

                /**
                 * Sets the value of the scale property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setScale(Integer value) {
                    this.scale = value;
                }

                /**
                 * Gets the value of the initialValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInitialValue() {
                    return initialValue;
                }

                /**
                 * Sets the value of the initialValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInitialValue(String value) {
                    this.initialValue = value;
                }

                /**
                 * Gets the value of the xPath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getXPath() {
                    return xPath;
                }

                /**
                 * Sets the value of the xPath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setXPath(String value) {
                    this.xPath = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ownedElements" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ownedElementRef" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="elementRef" use="required" type="{}nameType" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="contentType" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Empty"/>
         *             &lt;enumeration value="Any"/>
         *             &lt;enumeration value="Mixed"/>
         *             &lt;enumeration value="Element"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="occurrence" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="One"/>
         *             &lt;enumeration value="Zero or One"/>
         *             &lt;enumeration value="Zero or More"/>
         *             &lt;enumeration value="One or More"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="orderType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="elementTypeRef" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ownedElements",
            "text"
        })
        public static class Content {

            protected XmlDocumentType.Element.Content.OwnedElements ownedElements;
            protected String text;
            @XmlAttribute(name = "contentType", required = true)
            protected String contentType;
            @XmlAttribute(name = "occurrence", required = true)
            protected String occurrence;
            @XmlAttribute(name = "orderType", required = true)
            protected String orderType;
            @XmlAttribute(name = "elementTypeRef")
            protected String elementTypeRef;

            /**
             * Gets the value of the ownedElements property.
             * 
             * @return
             *     possible object is
             *     {@link XmlDocumentType.Element.Content.OwnedElements }
             *     
             */
            public XmlDocumentType.Element.Content.OwnedElements getOwnedElements() {
                return ownedElements;
            }

            /**
             * Sets the value of the ownedElements property.
             * 
             * @param value
             *     allowed object is
             *     {@link XmlDocumentType.Element.Content.OwnedElements }
             *     
             */
            public void setOwnedElements(XmlDocumentType.Element.Content.OwnedElements value) {
                this.ownedElements = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

            /**
             * Gets the value of the contentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentType() {
                return contentType;
            }

            /**
             * Sets the value of the contentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentType(String value) {
                this.contentType = value;
            }

            /**
             * Gets the value of the occurrence property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOccurrence() {
                return occurrence;
            }

            /**
             * Sets the value of the occurrence property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOccurrence(String value) {
                this.occurrence = value;
            }

            /**
             * Gets the value of the orderType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderType() {
                return orderType;
            }

            /**
             * Sets the value of the orderType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderType(String value) {
                this.orderType = value;
            }

            /**
             * Gets the value of the elementTypeRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElementTypeRef() {
                return elementTypeRef;
            }

            /**
             * Sets the value of the elementTypeRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElementTypeRef(String value) {
                this.elementTypeRef = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ownedElementRef" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="elementRef" use="required" type="{}nameType" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ownedElementRef"
            })
            public static class OwnedElements {

                @XmlElement(required = true)
                protected List<XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef> ownedElementRef;

                /**
                 * Gets the value of the ownedElementRef property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the ownedElementRef property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOwnedElementRef().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objeds of the following type(s) are allowed in the list
                 * {@link XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef }
                 * 
                 * 
                 */
                public List<XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef> getOwnedElementRef() {
                    if (ownedElementRef == null) {
                        ownedElementRef = new ArrayList<XmlDocumentType.Element.Content.OwnedElements.OwnedElementRef>();
                    }
                    return this.ownedElementRef;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="elementRef" use="required" type="{}nameType" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class OwnedElementRef {

                    @XmlAttribute(name = "elementRef", required = true)
                    protected String elementRef;

                    /**
                     * Gets the value of the elementRef property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getElementRef() {
                        return elementRef;
                    }

                    /**
                     * Sets the value of the elementRef property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setElementRef(String value) {
                        this.elementRef = value;
                    }

                }

            }

        }

    }

}