
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 10:27:57 AM IST 
//


package com.dataSwitch.xml.TalendProp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dataSwitch.xml.TalendProp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dataSwitch.xml.TalendProp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmiXMI }
     * 
     */
    public XmiXMI createXmiXMI() {
        return new XmiXMI();
    }

    /**
     * Create an instance of {@link XmiXMI.TalendPropertiesProcessItem }
     * 
     */
    public XmiXMI.TalendPropertiesProcessItem createXmiXMITalendPropertiesProcessItem() {
        return new XmiXMI.TalendPropertiesProcessItem();
    }

    /**
     * Create an instance of {@link XmiXMI.TalendPropertiesProperty }
     * 
     */
    public XmiXMI.TalendPropertiesProperty createXmiXMITalendPropertiesProperty() {
        return new XmiXMI.TalendPropertiesProperty();
    }

    /**
     * Create an instance of {@link XmiXMI.TalendPropertiesItemState }
     * 
     */
    public XmiXMI.TalendPropertiesItemState createXmiXMITalendPropertiesItemState() {
        return new XmiXMI.TalendPropertiesItemState();
    }

    /**
     * Create an instance of {@link XmiXMI.TalendPropertiesProcessItem.Process }
     * 
     */
    public XmiXMI.TalendPropertiesProcessItem.Process createXmiXMITalendPropertiesProcessItemProcess() {
        return new XmiXMI.TalendPropertiesProcessItem.Process();
    }

    /**
     * Create an instance of {@link XmiXMI.TalendPropertiesProperty.Author }
     * 
     */
    public XmiXMI.TalendPropertiesProperty.Author createXmiXMITalendPropertiesPropertyAuthor() {
        return new XmiXMI.TalendPropertiesProperty.Author();
    }

}