
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 10:27:57 AM IST 
//


package com.dataSwitch.xml.TalendProp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TalendProperties_Property">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="author">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="modificationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TalendProperties_ItemState">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TalendProperties_ProcessItem">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="process">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmi_version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="xmlns_xmi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns_TalendProperties" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "talendPropertiesProperty",
    "talendPropertiesItemState",
    "talendPropertiesProcessItem",
    "talendPropertiesRoutineItem",
    "talendPropertiesContextItem"
})
@XmlRootElement(name = "xmi:XMI")
public class XmiXMI {

    @XmlElement(name = "TalendProperties:Property", required = true)
    protected XmiXMI.TalendPropertiesProperty talendPropertiesProperty;
    @XmlElement(name = "TalendProperties:ItemState", required = true)
    protected XmiXMI.TalendPropertiesItemState talendPropertiesItemState;
    @XmlElement(name = "TalendProperties:ProcessItem", required = true)
    protected XmiXMI.TalendPropertiesProcessItem talendPropertiesProcessItem;
    @XmlElement(name = "TalendProperties:RoutineItem", required = true)
    protected XmiXMI.TalendPropertiesRoutineItem talendPropertiesRoutineItem;
    @XmlElement(name = "TalendProperties:ContextItem", required = true)
    protected XmiXMI.TalendPropertiesContextItem talendPropertiesContextItem;
    @XmlAttribute(name = "xmi:version")
    protected String xmiVersion;
    @XmlAttribute(name = "xmlns:xmi")
    protected String xmlnsXmi;
    @XmlAttribute(name = "xmlns:TalendProperties")
    protected String xmlnsTalendProperties;

    /**
     * Gets the value of the talendPropertiesProperty property.
     * 
     * @return
     *     possible object is
     *     {@link XmiXMI.TalendPropertiesProperty }
     *     
     */
    public XmiXMI.TalendPropertiesProperty getTalendPropertiesProperty() {
        return talendPropertiesProperty;
    }

    /**
     * Sets the value of the talendPropertiesProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmiXMI.TalendPropertiesProperty }
     *     
     */
    public void setTalendPropertiesProperty(XmiXMI.TalendPropertiesProperty value) {
        this.talendPropertiesProperty = value;
    }

    /**
     * Gets the value of the talendPropertiesItemState property.
     * 
     * @return
     *     possible object is
     *     {@link XmiXMI.TalendPropertiesItemState }
     *     
     */
    public XmiXMI.TalendPropertiesItemState getTalendPropertiesItemState() {
        return talendPropertiesItemState;
    }

    /**
     * Sets the value of the talendPropertiesItemState property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmiXMI.TalendPropertiesItemState }
     *     
     */
    public void setTalendPropertiesItemState(XmiXMI.TalendPropertiesItemState value) {
        this.talendPropertiesItemState = value;
    }

    /**
     * Gets the value of the talendPropertiesProcessItem property.
     * 
     * @return
     *     possible object is
     *     {@link XmiXMI.TalendPropertiesProcessItem }
     *     
     */
    public XmiXMI.TalendPropertiesProcessItem getTalendPropertiesProcessItem() {
        return talendPropertiesProcessItem;
    }

    /**
     * Sets the value of the talendPropertiesProcessItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmiXMI.TalendPropertiesProcessItem }
     *     
     */
    public void setTalendPropertiesProcessItem(XmiXMI.TalendPropertiesProcessItem value) {
        this.talendPropertiesProcessItem = value;
    }
    
    
    public XmiXMI.TalendPropertiesRoutineItem getTalendPropertiesRoutineItem() {
        return talendPropertiesRoutineItem;
    }

    /**
     * Sets the value of the talendPropertiesProcessItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmiXMI.TalendPropertiesProcessItem }
     *     
     */
    public void setTalendPropertiesRoutineItem(XmiXMI.TalendPropertiesRoutineItem value) {
        this.talendPropertiesRoutineItem = value;
    }
    
    
    
    public XmiXMI.TalendPropertiesContextItem getTalendPropertiesContextItem() {
        return talendPropertiesContextItem;
    }

    /**
     * Sets the value of the talendPropertiesProcessItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmiXMI.TalendPropertiesProcessItem }
     *     
     */
    public void setTalendPropertiesContextItem(XmiXMI.TalendPropertiesContextItem value) {
        this.talendPropertiesContextItem = value;
    }

    /**
     * Gets the value of the xmiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getXmiVersion() {
        return xmiVersion;
    }

    /**
     * Sets the value of the xmiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXmiVersion(String value) {
        this.xmiVersion = value;
    }

    /**
     * Gets the value of the xmlnsXmi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXmi() {
        return xmlnsXmi;
    }

    /**
     * Sets the value of the xmlnsXmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXmi(String value) {
        this.xmlnsXmi = value;
    }

    /**
     * Gets the value of the xmlnsTalendProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsTalendProperties() {
        return xmlnsTalendProperties;
    }

    /**
     * Sets the value of the xmlnsTalendProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsTalendProperties(String value) {
        this.xmlnsTalendProperties = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TalendPropertiesItemState {

        @XmlAttribute(name = "xmi:id")
        protected String xmiId;
        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="process">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "process"
    })
    public static class TalendPropertiesProcessItem {

        @XmlElement(required = true)
        protected XmiXMI.TalendPropertiesProcessItem.Process process;
        @XmlAttribute(name = "xmi:id")
        protected String xmiId;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "state")
        protected String state;

        /**
         * Gets the value of the process property.
         * 
         * @return
         *     possible object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public XmiXMI.TalendPropertiesProcessItem.Process getProcess() {
            return process;
        }

        /**
         * Sets the value of the process property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public void setProcess(XmiXMI.TalendPropertiesProcessItem.Process value) {
            this.process = value;
        }

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Process {

            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }

    
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class TalendPropertiesRoutineItem {

        @XmlElement(required = true)
        protected XmiXMI.TalendPropertiesRoutineItem.Content content;
        @XmlAttribute(name = "xmi:id")
        protected String xmiId;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "state")
        protected String state;

        /**
         * Gets the value of the process property.
         * 
         * @return
         *     possible object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public XmiXMI.TalendPropertiesRoutineItem.Content getContent() {
            return content;
        }

        /**
         * Sets the value of the process property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public void setContent(XmiXMI.TalendPropertiesRoutineItem.Content value) {
            this.content = value;
        }

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Content {

            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }
    
    
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "context"
    })
    public static class TalendPropertiesContextItem {

        @XmlElement(required = true)
        protected XmiXMI.TalendPropertiesContextItem.Context context;
        @XmlAttribute(name = "xmi:id")
        protected String xmiId;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "state")
        protected String state;

        /**
         * Gets the value of the process property.
         * 
         * @return
         *     possible object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public XmiXMI.TalendPropertiesContextItem.Context getContext() {
            return context;
        }

        /**
         * Sets the value of the process property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmiXMI.TalendPropertiesProcessItem.Process }
         *     
         */
        public void setProcess(XmiXMI.TalendPropertiesContextItem.Context value) {
            this.context = value;
        }

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Context {

            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="author">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="xmi_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="modificationDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "author"
    })
    public static class TalendPropertiesProperty {

        @XmlElement(required = true)
        protected XmiXMI.TalendPropertiesProperty.Author author;
        @XmlAttribute(name = "xmi:id")
        protected String xmiId;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "label")
        protected String label;
        @XmlAttribute(name = "creationDate")
        protected String creationDate;
        @XmlAttribute(name = "modificationDate")
        protected String modificationDate;
        @XmlAttribute(name = "version")
        protected Double version;
        @XmlAttribute(name = "statusCode")
        protected String statusCode;
        @XmlAttribute(name = "item")
        protected String item;
        @XmlAttribute(name = "displayName")
        protected String displayName;

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link XmiXMI.TalendPropertiesProperty.Author }
         *     
         */
        public XmiXMI.TalendPropertiesProperty.Author getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmiXMI.TalendPropertiesProperty.Author }
         *     
         */
        public void setAuthor(XmiXMI.TalendPropertiesProperty.Author value) {
            this.author = value;
        }

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the creationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreationDate() {
            return creationDate;
        }

        /**
         * Sets the value of the creationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreationDate(String value) {
            this.creationDate = value;
        }

        /**
         * Gets the value of the modificationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModificationDate() {
            return modificationDate;
        }

        /**
         * Sets the value of the modificationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModificationDate(String value) {
            this.modificationDate = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setVersion(Double value) {
            this.version = value;
        }

        /**
         * Gets the value of the statusCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusCode(String value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Author {

            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }

}