
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.05 at 03:01:37 PM IST 
//


package com.dataSwitch.talend.context;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contextParameter" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="xmi_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="comment" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="prompt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="promptNeeded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmi_version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="xmlns_xmi" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns_talendfile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmi_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="confirmationNeeded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contextParameter"
})
@XmlRootElement(name = "talendfile:ContextType")
public class TalendfileContextType {

    @XmlElement(required = true)
    protected List<TalendfileContextType.ContextParameter> contextParameter;
    @XmlAttribute(name = "xmi:version", required = true)
    protected String xmiVersion;
    @XmlAttribute(name = "xmlns:xmi", required = true)
    protected String xmlnsXmi;
    @XmlAttribute(name = "xmlns:talendfile", required = true)
    protected String xmlnsTalendfile;
    @XmlAttribute(name = "xmi:id", required = true)
    protected String xmiId;
    @XmlAttribute(name = "confirmationNeeded", required = true)
    protected boolean confirmationNeeded;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the contextParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objeds of the following type(s) are allowed in the list
     * {@link TalendfileContextType.ContextParameter }
     * 
     * 
     */
    public List<TalendfileContextType.ContextParameter> getContextParameter() {
        if (contextParameter == null) {
            contextParameter = new ArrayList<TalendfileContextType.ContextParameter>();
        }
        return this.contextParameter;
    }

    /**
     * Gets the value of the xmiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public String getXmiVersion() {
        return xmiVersion;
    }

    /**
     * Sets the value of the xmiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXmiVersion(String value) {
        this.xmiVersion = value;
    }

    /**
     * Gets the value of the xmlnsXmi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXmi() {
        return xmlnsXmi;
    }

    /**
     * Sets the value of the xmlnsXmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXmi(String value) {
        this.xmlnsXmi = value;
    }

    /**
     * Gets the value of the xmlnsTalendfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsTalendfile() {
        return xmlnsTalendfile;
    }

    /**
     * Sets the value of the xmlnsTalendfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsTalendfile(String value) {
        this.xmlnsTalendfile = value;
    }

    /**
     * Gets the value of the xmiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmiId() {
        return xmiId;
    }

    /**
     * Sets the value of the xmiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmiId(String value) {
        this.xmiId = value;
    }

    /**
     * Gets the value of the confirmationNeeded property.
     * 
     */
    public boolean isConfirmationNeeded() {
        return confirmationNeeded;
    }

    /**
     * Sets the value of the confirmationNeeded property.
     * 
     */
    public void setConfirmationNeeded(boolean value) {
        this.confirmationNeeded = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="xmi_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="comment" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="prompt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="promptNeeded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ContextParameter {

        @XmlAttribute(name = "xmi:id", required = true)
        protected String xmiId;
        @XmlAttribute(name = "comment", required = true)
        protected String comment;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "prompt", required = true)
        protected String prompt;
        @XmlAttribute(name = "promptNeeded", required = true)
        protected boolean promptNeeded;
        @XmlAttribute(name = "type", required = true)
        protected String type;
        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the xmiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmiId() {
            return xmiId;
        }

        /**
         * Sets the value of the xmiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmiId(String value) {
            this.xmiId = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComment(String value) {
            this.comment = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the prompt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrompt() {
            return prompt;
        }

        /**
         * Sets the value of the prompt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrompt(String value) {
            this.prompt = value;
        }

        /**
         * Gets the value of the promptNeeded property.
         * 
         */
        public boolean isPromptNeeded() {
            return promptNeeded;
        }

        /**
         * Sets the value of the promptNeeded property.
         * 
         */
        public void setPromptNeeded(boolean value) {
            this.promptNeeded = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}